version: '3.4'

volumes:
  kapgdata:

services:

  db:
    build:
      context: .
      target: db
    volumes:
      - kapgdata:/var/lib/postgresql/data

  rest:
    build:
      context: .
      target: base
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      PGHOST: db
      PGUSER: postgres
      PGDATABASE: postgres
    ports:
      - '3000:3000'
    depends_on:
      - db
    command: yarn run dev:rest

  web:
    build:
      context: .
      target: base
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      API_URL: http://localhost:3000
    ports:
      - '8080:8080'
    depends_on:
      - rest
    command: yarn run dev:web
